name: models
description: Contains shared models between backend and mobile application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # Data class generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  # Code gen
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

  # Testing
  mocktail: ^0.3.0
  test: ^1.19.2

  # Linter
  very_good_analysis: ^3.1.0
