name: models
description: Contains shared models between backend and mobile application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Data class generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  # Code gen
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  # Testing
  mocktail: ^1.0.3
  test: ^1.25.2

  # Linter
  very_good_analysis: ^5.1.0
