name: backend
description: Dart Frog Playground Backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0

  # Data Models
  models:
    path: packages/models/

  # DB
  mongo_dart: ^0.10.0

  # Functional programming
  fpdart: ^1.1.0

  # Utils
  dart_jsonwebtoken: ^2.13.0
  encrypt: ^5.0.3
  uuid: ^4.3.3

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
