name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0

  # Data Models
  models:
    path: packages/models/
  # DB
  mongo_dart: ^0.8.2

  # Functional programming
  dartz: ^0.10.1

  # Utils
  dart_jsonwebtoken: ^2.6.3
  encrypt: ^5.0.1
  uuid: ^3.0.7

  # Data class generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

  # Code gen
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
